language: php
dist: trusty

php:
    - 7.2
    - 7.3
    - 7.4
    - nightly

matrix:
    allow_failures:
        - php: nightly

include:
        - php: 7.2
          env: DEPENDENCIES="lowest"

before_script:
    - if php -v | grep -q "Xdebug"; then phpenv config-rm xdebug.ini; fi
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction
    - if [ "$DEPENDENCIES" = "lowest" ]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction; fi;

script:
    - make travis

after_success:
    - bash <(curl -s https://codecov.io/bash)

cache:
    directories:
        - $HOME/.composer/cache
