language: php

php:
    - 7.2
    - 7.3
    - 7.4
    - nightly

matrix:
    allow_failures:
        - php: nightly

include:
        - php: 7.2
          env: DEPENDENCIES="lowest"

before_install:
    - git clone -b stable https://github.com/jedisct1/libsodium.git
    - cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..

install:
    - pecl install libsodium
    - echo "extension=sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
    - if php -v | grep -q "Xdebug"; then phpenv config-rm xdebug.ini; fi
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction
    - if [ "$DEPENDENCIES" = "lowest" ]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction; fi;

script:
    - make travis

after_success:
    - bash <(curl -s https://codecov.io/bash)

cache:
    directories:
        - $HOME/.composer/cache
